import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { sanityStaticProps, useSanityQuery, PortableText } from '../lib/sanity';
import { groq } from 'next-sanity';
import { client } from '../lib/sanity';
import imageUrlBuilder from '@sanity/image-url';
import { getSanityImage } from '@/lib/getSanityImage';

const builder = imageUrlBuilder(client);
function urlFor(source) {
  return builder.image(source).width(720);
}

const inter = Inter({ subsets: ['latin'] });

export default function Home(props) {
  /*   const { data, loading, error } = useSanityQuery(myQuery, props); */
  /*   console.log(props.data[0].images[0].asset._ref); */
  const images = props.data[0].images;

  const img = urlFor(props.data[0].images[0].asset._ref);
  console.log(img);
  /*   console.log(img); */

  /* console.log(props); */
  return (
    <>
      <Head>
        <title>Aurore Legentil - Photographie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {images.map(({ asset }, index) => {
          const src = urlFor(asset._ref);

          return <img src={src} alt="" key={index}></img>;
        })}
      </main>
    </>
  );
}

const myQuery = groq`*[_type == 'project']`;

export const getStaticProps = async (context) => ({
  props: await sanityStaticProps({ context, query: myQuery }),
});
