import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { sanityStaticProps, useSanityQuery, PortableText } from '../lib/sanity';
import { groq } from 'next-sanity';

import { getSanityImage } from '@/lib/getSanityImage';

const inter = Inter({ subsets: ['latin'] });

export default function Home(props) {
  /*   const { data, loading, error } = useSanityQuery(myQuery, props); */
  /*   console.log(props.data[0].images[0].asset._ref); */
  const images = props.data[0].images;

  const img2 = getSanityImage(props.data[0].images[0].asset._ref);
  console.log(img2);
  /*   console.log(img); */

  /* console.log(props); */
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/*    {<img src={img} alt="ekki" />} */}

        {/*    <img
          src="https://cdn.sanity.io/images/h714pqdi/production/f2f886a3a6bb6438a3a3a134e3a3570db60b70b7-2278x1534.jpg"
          alt="ekki"
        /> */}
        {/*  <img src={img2} alt="ekki" /> */}
        {images.map(({ asset }, index) => {
          const src = getSanityImage(asset._ref);

          return <img src={src} alt="" key={index}></img>;
        })}
      </main>
    </>
  );
}

const myQuery = groq`*[_type == 'project']`;

export const getStaticProps = async (context) => ({
  props: await sanityStaticProps({ context, query: myQuery }),
});
